security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:   ^/api
            anonymous: ~

        login:
            pattern:   ^/login$
            anonymous: ~

        main:
            pattern: ^/
            provider: db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            remember_me:
                secret: "%secret%"
                path: /

    access_control:
        - { path: ^/projects, roles: ROLE_USER }