AppBundle\Entity\Project:
  properties:
    name:
      - NotBlank:
          message: Please enter a name
    frameStart:
      - Regex:
          pattern: '~^\d+$~'
          message: Please enter a valid number
    frameEnd:
      - Regex:
          pattern: '~^\d+$~'
          message: Please enter a valid number
    format:
      - NotBlank:
          message: Please choose an image format
      - Choice:
          callback: getImageFormats
          message: Please choose an image format from the list
    engine:
      - NotBlank:
          message: Please choose a rendering engine
      - Choice:
          callback: getEngines
          message: Please choose a rendering engine from the list

AppBundle\Entity\User:
  properties:
    username:
      - NotBlank:
          message: Please enter an username
    password:
      - NotBlank:
          message: Please enter a password
    email:
      - NotBlank:
          message: Please enter an email adress
      - Email:
          message: Please enter a valid mail address