AppBundle\Entity\Task:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\TaskRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        frameNumber:
            type: integer
        status:
            type: string
            length: '20'
        runtime:
            type: float
        remaining:
            type: float
        progress:
            type: float

    manyToOne:
        project:
            targetEntity: AppBundle\Entity\Project
            inversedBy: frames
            joinColumn:
                name: projectId
                referencedColumnName: id
    lifecycleCallbacks: {  }
